services:
  bookmark-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookmark-be
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - bookmark-network
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "const http = require('http'); http.get('http://localhost:3001', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.bookmark-be.rule=Host(`api.bookmark.local`)'
      - 'traefik.http.services.bookmark-be.loadbalancer.server.port=3001'

networks:
  bookmark-network:
    driver: bridge
