
app = "bookmark-manager-backend"
primary_region = "sin"  # Singapore - change this to "hkg" for Hong Kong

[build]

[env]
  NODE_ENV = "production"
  PORT = "3001"
  API_PREFIX = "api/v1"
  SWAGGER_TITLE = "Bookmark Manager API"
  SWAGGER_DESCRIPTION = "Backend API for managing bookmarks with full CRUD operations"
  SWAGGER_VERSION = "1.0"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/v1"

[processes]
  app = "node dist/main.js"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  release_command = "echo 'Deployment completed successfully'"

[metrics]
  port = 9091
  path = "/metrics"
