app = 'bookmark-manager-backend'
primary_region = 'sin'

[build]
  dockerfile = './Dockerfile'

[deploy]
  release_command = "echo 'Deployment completed successfully'"

[env]
  API_PREFIX = 'api/v1'
  NODE_ENV = 'production'
  PORT = '3001'
  SWAGGER_DESCRIPTION = 'Backend API for managing bookmarks with full CRUD operations'
  SWAGGER_TITLE = 'Bookmark Manager API'
  SWAGGER_VERSION = '1.0'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 10
    soft_limit = 5

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/v1'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
