services:
  bookmark-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: bookmark-fe
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - bookmark-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.bookmark-fe.rule=Host(`localhost`)'
      - 'traefik.http.services.bookmark-fe.loadbalancer.server.port=80'

networks:
  bookmark-network:
    driver: bridge
    name: bookmark-network

# Optional: Add volumes for persistent data
volumes:
  nginx_cache:
    driver: local
